### ISSUE TITLE
Type com.google.protobuf.LazyStringArrayList$ByteArrayListView is defined multiple times

### ISSUE THREAD

**Issue by antonPolosin** [plaid/plaid-link-android#200]
# The problem

Compilation error after updating Plaid SDK to 3.6.0.  Error `Type com.google.protobuf.LazyStringArrayList$ByteArrayListView is defined multiple times: `
